-- Création de la table des edt_messages
CREATE TABLE IF NOT EXISTS public.edt_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID NOT NULL REFERENCES public.edt_user(id) ON DELETE CASCADE,
    receiver_id UUID NOT NULL REFERENCES public.edt_user(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index pour accélérer les requêtes
CREATE INDEX IF NOT EXISTS idx_messages_sender_receiver ON public.edt_messages(sender_id, receiver_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.edt_messages(created_at);

-- Activer la sécurité RLS
ALTER TABLE public.edt_messages ENABLE ROW LEVEL SECURITY;

-- Autoriser la lecture de ses propres messages
CREATE POLICY "Les utilisateurs peuvent lire leurs messages"
ON public.edt_messages
FOR SELECT
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- Autoriser l'envoi de messages en son nom
CREATE POLICY "Les utilisateurs peuvent envoyer des messages"
ON public.edt_messages
FOR INSERT
WITH CHECK (auth.uid() = sender_id);
